In [41]:
import numpy as np
from sklearn.linear_model import LinearRegression
arr = np.array(((1,1),(2,2),(3,3),(4,4),(5,5)))

arr = np.array(((1,2),(2,1),(3,3),(4,5),(5,5)))

regressor = LinearRegression()
x = arr[:,0]
y = arr[:,1]
print(x)
print(y)

# x = x.reshape(1,-1)
x = x.reshape(5,1)
y = y.reshape(5,1)

print(x)
print(y)

regressor.fit(x, y)

[1 2 3 4 5]
[2 1 3 5 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[2]
 [1]
 [3]
 [5]
 [5]]


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
regressor.intercept_

array([0.2])

In [44]:
regressor.coef_

array([[1.]])

In [45]:
regressor.score(x,y)

0.78125

In [46]:
arr = np.array(((1,1,2),(2,2,4),(3,3,6),(4,4,9),(5,5,9)))

regressor = LinearRegression()
x = arr[:,:2]
y = arr[:,2]
print(x)
print(y)


[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[2 4 6 9 9]


In [47]:
y = y.reshape(5,1)
print(y)
regressor.fit(x, y)

[[2]
 [4]
 [6]
 [9]
 [9]]


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [48]:
regressor.intercept_

array([0.3])

In [49]:
regressor.coef_

array([[0.95, 0.95]])

In [50]:
regressor.score(x,y)

0.9500000000000001