In [1]:
import numpy as np
arr = np.array(((1,1,0),(2,1,0),(3,3,1),(4,5,1),(5,4,1)))

In [2]:
from sklearn.linear_model import LogisticRegression

In [6]:
x = arr[:,:2]
x

array([[1, 1],
       [2, 1],
       [3, 3],
       [4, 5],
       [5, 4]])

In [9]:
y = arr[:,2]
y

array([0, 0, 1, 1, 1])

In [10]:
reg = LogisticRegression()

In [11]:
reg.fit(x,y)

/home/sujan/Desktop/Training/pyvenv/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
reg.coef_

array([[0.06962555, 0.54803309]])

In [13]:
reg.intercept_

array([-0.59809015])

In [16]:
reg.score(x,y)

0.6

In [17]:
reg.predict(x)

array([1, 1, 1, 1, 1])