In [30]:
import numpy as np

arr = np.array(((1,1,0), (0, 1, 0), (5, 3, 1), (4,5, 1), (5,4, 1)))

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
x = arr[:,:2]

In [33]:
x

array([[1, 1],
       [0, 1],
       [5, 3],
       [4, 5],
       [5, 4]])

In [34]:
y = arr[:,2]

In [35]:
y

array([0, 0, 1, 1, 1])

In [36]:
reg = LogisticRegression()

In [37]:
reg.fit(x,y)

c:\users\goldy\desktop\data_science\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [38]:
reg.coef_

array([[0.57872068, 0.10241392]])

In [39]:
reg.intercept_

array([-0.64072045])

In [40]:
reg.score(x,y)

0.8

In [41]:
reg.predict(x)

array([1, 0, 1, 1, 1])