In [1]:
import numpy as np

arr = np.array(((3,1,1), (1, 3, 1), (4, 2, 0), (2,4, 0)))

In [2]:
from sklearn.svm import SVC, LinearSVC

In [3]:
linear_svc = LinearSVC()

In [4]:
x = arr[:,:2]

In [5]:
x

array([[3, 1],
       [1, 3],
       [4, 2],
       [2, 4]])

In [6]:
y = arr[:,2]

In [7]:
y

array([1, 1, 0, 0])

In [8]:
linear_svc.fit(x,y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [9]:
linear_svc.coef_

array([[-0.2482663 , -0.24827535]])

In [10]:
linear_svc.intercept_

array([1.10337849])

In [11]:
linear_svc.score(x,y)

1.0